config/routes.rb
Rails.application.routes.draw do
  get 'tests/top'
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about" 
  get "/search" => "searches#search"
  
  resources :users,only: [:index,:show,:edit,:update] do 
    resource :relationships, only: [:create,:destroy]
   get 'followings' => 'relationships#followings',as: 'followings'
   get 'followers' => 'relationships#followers' ,as: 'followers'
   end  
  resources :groups do
   get "join" => "groups#join"
   get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  resources :messages,only: [:create]
  resources :rooms,only: [:create,:show]
  
  resources :books,only: [:index,:create,:show,:edit,:update,:destroy] do
    resource :favorites ,only:[:create, :destroy]
    resources :book_comments,only: [:create,:destroy]
  end  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments ,dependent: :destroy
  has_many :favorites ,dependent: :destroy
  
  has_many :favorite_users, through: :favorites, source: :user
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  
  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 }
  
  is_impressionable
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true, uniqueness: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :content, presence: true,length: { maximum: 140 }
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books,dependent: :destroy
  attachment :profile_image
  has_many :book_comments ,dependent: :destroy
  has_many :favorites ,dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :re_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :re_relationships, source: :follower
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :group_users
  has_many :groups, through: :group_users
 
  def follow(user_id)
    relationships.create(followed_id: user_id)
    
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include? (user)
  end  
  
  
  validates :name,length: { minimum: 2, maximum: 20 } ,uniqueness: true
  validates :introduction,length: { maximum: 50 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  impressionist :actions=> [:index,:show]
  
  def index
    @books = Book.all
    @book_new = Book.new
    @user = current_user
    
    @ranks = Book.includes(:favorite_users).sort {|a,b| 
    (b.favorite_users.includes(:favorites).size) <=> (a.favorite_users.includes(:favorites).size)}
    
    @books.each do |book|
    impressionist(book, nil, unique: [:ip_address])
    end
  end

  def create
    @books = Book.all
    @book_new = Book.new(book_params)
    @book_new.user_id= current_user.id
   if @book_new.save
      flash[:notice]="You have created book successfully."
       redirect_to book_path(@book_new.id)
   else
       @user = current_user
       render :index
   end
  end

  def show
     @book = Book.find(params[:id])
     @user = @book.user
     @book_new = Book.new
     @comment = BookComment.new
     impressionist(@book, nil, unique: [:ip_address])
  end

  def edit
     @book = Book.find(params[:id])
    unless @book.user == current_user
    redirect_to books_path
    end
  end

  def update
    @book=Book.find(params[:id])
   if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id)
   else
    render :edit
   end
  end

  def destroy
    @book=Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

   private

  def book_params
    params.require(:book).permit(:title,:body,:user_id)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about 
  end  
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @book_new = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
     
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id != current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
    
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
     render :edit
    else
     redirect_to user_path(current_user)  
    end  
    # unless @user == current_user
    #   redirect_to  user_path(@user.id)
    # end 上記に
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
    else
    render :edit
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

   private

  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end

  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, :fill, 80, 80 ,fallback: "no_image.jpg" %>
<table class="table">
  <tr></tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, user_followers_path(user.id) %></th>
  </tr>
</table>

<% unless user == current_user %>
<div class="row">
<% if current_user.following?(user) %>
   <%=link_to "UnFollow",user_relationships_path(user.id),method: :delete ,class: "btn btn-sm btn-info"%>
<% else %>
    <%=link_to "Follow",user_relationships_path(user.id),method: :post ,class: "btn btn-sm btn-info"%>
<% end %>
</div>
<% else %>
<div class="row">
<%=link_to"", edit_user_path(user.id), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
</div>
<% end %>

<% if user.id != current_user.id %>
 <% if (current_user.following? user) && (user.following? current_user)  %>
  <% if @isRoom == true %>
   <%=link_to "chatを始める",room_path(@roomId)%>
  <% else %>
    <%= form_with model: @room do |f| %>
      <%= fields_for @entry do |e| %>
      <%= e.hidden_field :user_id, value: user.id %>
      <% end %>
    <%= f.submit "chat start" %>
    <% end %>
  <% end %>
 <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

<h2>User info</h2>
<% if @user.errors.any? %>
 <h3 class="text-danger"><%= @user.errors.count %>errors prohibited this obj from being saved:</h3> 
  <% @user.errors.full_messages.each do |message| %>
  <li class="text-danger"><%= message %></li>
  <% end %>
<% end %>

<%= form_with model:@user, local:true do |f| %>

<div class="form-group">
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName",class:"form-control name"%>
</div>  
<div class="form-group">  
  <label for="inputImage">Image</label>
  <%= f.attachment_field :profile_image,class:"form-control-file image"%>
</div>  
<div class="form-group">  
  <label for="inputName">Introduction</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction",class:"form-control introduction"%>
</div>  
<div class="form-group">  
  <%= f.submit "Update User" ,class:"btn btn-secondary"%>
</div>
<% end %>

</div>
</div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
  <div class="col-md-3">
   <%= render 'users/info', user: @user %>
   <%= render 'books/new', book: @book %>
</div>
<div class="col-md-8 offset-md-1">
<h2>Users</h2>
<div><%= link_to"グループ作成",new_group_path %> | <%= link_to "グループ一覧",groups_path %></div>
<table class="table">
  <thead>
  <tr>
     <th>image</th>
     <th>name</th>
     <th colspan="3"></th>
   </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
   <tr>
    <td><%= attachment_image_tag user, :profile_image,fallback: "no_image.jpg",size:"40x40" %></td>
    <td><%= user.name %></td>
    <td>フォロー:<%= user.followings.count %></td>
    <td>フォロワー:<%= user.followers.count %></td>

    <td>
    <% unless user == current_user %>
     <% if current_user.following?(user) %>
     <%=link_to "UnFollow",user_relationships_path(user.id),method: :delete %>
     <% else %>
     <%=link_to "Follow",user_relationships_path(user.id),method: :post %>
     <% end %>
    <% end %>
     </td>
    <td><%=link_to "Show",user_path(user.id) %></td>
  </tr>

  <% end %>

 </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <%= render 'users/info', user: @user %>
   <%= render 'books/new', book: @book %>
  </div>  
 
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class=table table-hover table-inverse>
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
     </tr>
    </thead>
  
    <tbody>
     <tr>
      <% @books.each do |book| %>
     
      <td><%=link_to user_path(@user.id) do %>
          <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg",size:"40x40"%>
          <% end %>
      </td>
      <td><%=link_to book.title,book_path(book.id) %></td>
      <td><%= book.body %></td>
      <td></td>
      <td>コメント数：<%= book.book_comments.count %></td>
     </tr>
      <% end %>
    </tbody>
   </table>
   </div>
 </div>
 </div>