config/routes.rb
Rails.application.routes.draw do
  get 'tests/top'
  get 'searches/search'
  devise_for :users
  root to: 'homes#top'
  get "home/about" => "homes#about" 
  get "/search" => "searches#search"
  
  resources :users,only: [:index,:show,:edit,:update] do 
    resource :relationships, only: [:create,:destroy]
   get 'followings' => 'relationships#followings',as: 'followings'
   get 'followers' => 'relationships#followers' ,as: 'followers'
   end  
  resources :groups do
   get "join" => "groups#join"
   get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  
  resources :messages,only: [:create]
  resources :rooms,only: [:create,:show]
  
  resources :books,only: [:index,:create,:show,:edit,:update,:destroy] do
    resource :favorites ,only:[:create, :destroy]
    resources :book_comments,only: [:create,:destroy]
  end  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments ,dependent: :destroy
  has_many :favorites ,dependent: :destroy
  
  has_many :favorite_users, through: :favorites, source: :user
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  
  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 }
  
  is_impressionable
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true, uniqueness: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :content, presence: true,length: { maximum: 140 }
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
  
end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books,dependent: :destroy
  attachment :profile_image
  has_many :book_comments ,dependent: :destroy
  has_many :favorites ,dependent: :destroy
  has_many :favorite_books, through: :favorites, source: :book

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :re_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :re_relationships, source: :follower
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  
  has_many :group_users
  has_many :groups, through: :group_users
 
  def follow(user_id)
    relationships.create(followed_id: user_id)
    
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include? (user)
  end  
  
  
  validates :name,length: { minimum: 2, maximum: 20 } ,uniqueness: true
  validates :introduction,length: { maximum: 50 }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# flash.each do |key, value| %>
    <%#= content_tag(:div, value, class: "#{key}") %>
    <%# end %>
   <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
    <a class="navbar-brand" href="/">Bookers</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
                aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse " id="navbarNavDropdown" style>
    <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>
      <li>
        <%= link_to "Home", user_path(current_user) ,class:"fas fa-home nav-link text-light" %>
      </li>
      <li>
        <%= link_to "Users", users_path ,class:"fas fa-users nav-link text-light"%>
      </li>
      <li>
        <%= link_to "Books", books_path,class:"fas fa-book-open nav-link text-light" %>
      </li>
      <li>
        <%= link_to "logout", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light"%>
      </li>

     <%else%>
    　<li>
        <%= link_to "Home", "/" ,class:"fas fa-home nav-link text-light"%>
      </li>
      <li>
        <%= link_to "About", "/home/about" ,class:"fas fa-link nav-link text-light"%>
      </li>
      <li>
        <%= link_to "sign up", new_user_registration_path ,class:"fas fa-user-plus nav-link text-light"%>
      </li>
      <li>
        <%= link_to "login", new_user_session_path,class:"fas fa-sign-in-alt nav-link text-light" %>
      </li>
     <% end %>
     </ul>
     </div>
     </div>
     </nav>
     </header>

     <main>
     <p class="text-success",id="notice"><%= notice %>
      <p class="text-danger" ,id="alert"><%= alert %>
    <div class="container">  
    <div class="row">
     <div class="mx-auto">
      <% if user_signed_in? %>
       <%= form_with url: search_path, method: :get,local: true do |f| %>
       <%= f.text_field 'search[value]',placeholder:"キーワードを入力" %>
       <%= f.select 'search[model]',options_for_select({"User" => "user","Book" => "book"}),include_blank:"選択" %>
       <%= f.select 'search[how]' ,options_for_select({"完全一致"=>"perfect","前方一致"=>"forward","後方一致"=>"backward","部分一致"=>"partical"}),include_blank:"選択"%>
       <%= f.submit :"検索" %>
       <% end %>
      <% end %>  
     </div>
    </div>
    </div>
      <%= yield %>
     </main>

     <footer>
       <div class="container mt-5">
         <div class="row">
           <div class="mx-auto">
             <p>Copy Right Inflatop.inc</p>
           </div>
         </div>
       </div>
     </footer>
  </body>

</html>